UserCore/urls.py
from django.urls import path
from .views import CustomTokenObtainPairView, TokenRefreshView,ProtectedView

urlpatterns = [
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('protected_resource/', ProtectedView.as_view(), name='protected-resource'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookapi/', include('booking.urls')),
    path('courtapi/',include('court.urls')),
    path('auth/',include('UserCore.urls')),

]

booking/urls.py
from django.contrib import admin
from django.urls import path
from .views import create_booking,Listing_booking,Update_booking,get_booking_detail,list_user_booking, BookList


app_name = 'booking'
urlpatterns = [
    path('bookinglist/',Listing_booking, ),

    path('create/', create_booking),
    path('update/<int:pk>/', Update_booking),
    path('booking/<int:pk>/', get_booking_detail),
    path('listuser/',list_user_booking),


    path('booking_list/',BookList, name='booking_list')

]

court/urls.py
from django.contrib import admin
from django.urls import path
from .views import list_Court,Update_court,delete_court
from . import views

urlpatterns = [
    path('list/',list_Court),
    path('update/<int:pk>/',Update_court),
    path('delete/<int:pk>/',delete_court),
    path('search/',views.Search_Court)
    
]

UserCore/models.py
from django.db import models

# Create your models here.

booking/models.py
from django.db import models
from django.contrib.auth.models import User

from court.models import Court
# Create your models here.


class Booking(models.Model):

    StatusType = [
        ('C','Confirm'),
        ('P','Pending'),
        ('Ca','Cancel')
    ]
    PaymentStatus = [
        ('U','Unpaid'),
        ('P','Paid')
    ]
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    court = models.ForeignKey(Court, on_delete= models.CASCADE)
    booking_date = models.DateTimeField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    total_cost = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.CharField(max_length=3, choices = StatusType)
    payment_status = models.CharField(max_length=2, choices = PaymentStatus)
    Created_at = models.DateTimeField()
    update_at = models.DateTimeField

court/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    city = models.CharField(max_length=250)
    district = models.CharField(max_length=255)

    def __str__(self) :
        return self.city

class Court(models.Model):

    CourtType = [
        ("5","5v5"),
        ("7","7v7"),
        ("11","11v11")
    ]


    court_name = models.CharField(max_length=255)
    court_type = models.CharField(max_length=3, choices= CourtType)
    location = models.ForeignKey(Location,on_delete = models.CASCADE )
    availability = models.BooleanField()
    create_at = models.DateTimeField()
    updated_at = models.DateTimeField()
 
    def __str__(self) :
        return self.court_name

UserCore/views.py
from django.shortcuts import render
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView
from rest_framework import permissions
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response

# Create your views here.
class CustomTokenObtainPairView(TokenObtainPairView ):
    permission_classes = [permissions.AllowAny]

class TokenRefreshView(TokenRefreshView):
    permission_classes= [permissions.AllowAny]


class ProtectedView(APIView): 
    permission_classes=[IsAuthenticated]

    def get(self, request):
        return Response({'message': 'You have authenticated '})

booking/views.py
from django.shortcuts import render
from .serializer import BookingSerializer,UpdateBookingSerializer,UserSerializer
from .models import Booking
from rest_framework.response import Response
from rest_framework.decorators import api_view,permission_classes
from rest_framework import status
from django.contrib.auth.models import User
from rest_framework.permissions import AllowAny

# Create your views here.

@api_view(['POST'])
def create_booking(request): 

    serializer = BookingSerializer(data = request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data,status = status.HTTP_201_CREATED) 
    else: 
        return Response(serializer.errors, status= status.HTTP_400_BAD_REQUEST)
    
@api_view(['GET'])
@permission_classes([AllowAny])
def Listing_booking(request):

    queyset = Booking.objects.all()
    serializer = BookingSerializer(queyset,many=True)
     
    return Response(serializer.data)


@api_view(['POST','GET'])
def Update_booking(request,pk):
    if request.method == 'GET' :
        queryset = Booking.objects.filter(pk=pk)
        serializer = BookingSerializer(queryset,many=True)

        return Response(serializer.data)
    if request.method == 'POST':
        booking = Booking.objects.get(pk=pk)
        serializer = UpdateBookingSerializer(booking,data = request.data)

        if serializer.is_valid():
            serializer.save()
        
            return Response(serializer.data)
        else: 
            return Response(serializer.errors)

# Action Controller, View
@api_view(['GET'])
def get_booking_detail(request, pk):
    # get data through model from database
    queryset = Booking.objects.filter(pk=pk)

    # Apply business logic

    # serialize data to convert it to what we want
    serializer = BookingSerializer(queryset, many=True)

    # Response back to endpoint
    return Response(serializer.data)


@api_view(['GET'])
def list_user_booking(reqest):
    queryset = User.objects.all()
    serializer = UserSerializer(queryset , many= True)
    return Response(serializer.data)
 
    
   
  

court/views.py
from django.shortcuts import render
from .models import Court
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status,generics,filters
from django.contrib.auth.models import User
from .serializer import CourtSerializer,DeleteSerializer,SearchSerializer
from rest_framework.permissions import IsAuthenticated
# Create your views here.


@api_view(['GET'])
def list_Court (request): 
        
        queryset = Court.objects.all()
        serializers = CourtSerializer(queryset, many = True)
        return Response(serializers.data)


@api_view(['PUT','GET'])
def Update_court(request,pk):
        
         
        if request.method == 'PUT':
                court = Court.objects.get(pk=pk)
                serailizer = CourtSerializer(court,data = request.data)
                if serailizer.is_valid():
                        serailizer.save()
                        return Response(serailizer.data,status=status.HTTP_201_CREATED)
                return Response(serailizer.data, status = status.HTTP_400_BAD_REQUEST)
        if request.method == 'GET':
                queryset = Court.objects.get(pk=pk)
                serailizer = CourtSerializer(queryset)

                return Response(serailizer.data)
                

@api_view(['DELETE'])
def delete_court(request,pk): 
        queryset = Court.objects.get(pk=pk)
        print(queryset),

        queryset.delete()
        return Response({'msg': 'Person deleted successfully'}, status=status.HTTP_204_NO_CONTENT)



@api_view([ 'POST'])
def Search_Court(request):
    if request.method == 'POST':
        court_name = request.data.get('court_name')         
        courts = Court.objects.filter(court_name__icontains=court_name)
        serializer = SearchSerializer(courts , many= True)
        return Response(serializer.data, status=status.HTTP_200_OK)
       
print(Court.objects.filter(court_name = 'Camnou'))

UserCore/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    {% block content %}

    <h2>Register </h2>
    <form method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p}} This is using for listing all the input here-->
        <div class="form-group">
            <label for="id_username">Username</label>
            {{ form.username }}
          </div>
      
          <div class="form-group">
            <label for="id_password">Password</label>
            {{ form.password }}
          </div>
        <button>login</button>
    </form>
{% endblock %}
</body>
</html>

UserCore/templates/register.html
{% block content %}

    <h2>Register </h2>
    <form method="POST">
        {% csrf_token %}
        
        <!-- Rendering fields with labels -->
        <div>
            <label for="id_email">Email</label>
            {{ form.email }}
        </div>

        <div>
            <label for="id_username">Username</label>
            {{ form.username }}
        </div>

        <div>
            <label for="id_password1">Password</label>
            {{ form.password1 }}
        </div>

        <div>
            <label for="id_password2">Confirm Password</label>
            {{ form.password2 }}
        </div>

        <!-- Submit button -->
        <button type="submit">Register</button>
    </form>
{% endblock %}

booking/templates/bookinglist.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
</head>
<body>
    


    {% block content %}
        {% if user.is_authenticated %}

            <nav class="bg-white border-gray-200 dark:bg-gray-900">
                <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

                    <a href="" class="flex items-center space-x-3 rtl:space-x-reverse">
                        
                        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Court Booking</span>
                    </a>

                <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

                    <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                        <div class="text-white w-fit p-2 flex justify-between gap-5 items-center">
                            {% if user.is_authenticated %}
                                <h1>Welcome, {{ user.username }}!</h1>
                            {% else %}
                                <h1>Welcome, Guest!</h1>
                            {% endif %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                            </svg>   
                        </div>
                        

                    </button>
            
                </div>
                <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
                    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        
                        <li>
                            <a href="{% url 'court:courtlist'%}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Court</a>
                        </li>
                        <li>
                            <a href="" class="block py-2 px-3 text-white rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Booking List</a>
                        </li>

                    </ul>
                </div>
                </div>
            </nav>

            {% for booking in booking %}
                <div class=" flex justify-center p-2">
                     <a href="#" class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="https://www.barcelona-tourist-guide.com/images/int/sport/barcelona-fc/L/fc-barcelona-0603.jpg" alt="">
                    <div class="flex flex-col justify-between p-4 leading-normal">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ booking.court }}</h5>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{booking.booking_date}}</p>
                     </div>
                    </a> 
                </div>
              
            {%endfor%}


        {% else %}
            <h1>Please login</h1>
        {% endif %}
    {% endblock %}
</body>
</html>

court/templates/court.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
</head>
<body>
    {% block content %}
        {% if user.is_authenticated %}

            <nav class="bg-white border-gray-200 dark:bg-gray-900">
                <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

                    <a href="" class="flex items-center space-x-3 rtl:space-x-reverse">
                        
                        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Court Booking</span>
                    </a>

                <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

                    <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                        <div class="text-white w-fit p-2 flex justify-between gap-5 items-center">
                            {% if user.is_authenticated %}
                                <h1>Welcome, {{ user.username }}!</h1>
                            {% else %}
                                <h1>Welcome, Guest!</h1>
                            {% endif %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                                 <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                            </svg>   
                        </div>
                        

                    </button>
            
                </div>
                <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
                    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        
                        <li>
                            <a href="" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Court</a>
                        </li>
                        <li>
                            <a href="{% url 'booking:booking_list' %}" class="block py-2 px-3 text-white rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Booking List</a>
                        </li>

                    </ul>
                </div>
                </div>
            </nav>

            <div>
                <div class="flex flex-row gap-5 p-5">
                    {% for court in court %}

                    <div class="relative flex flex-col my-6 bg-white shadow-sm border border-slate-200 rounded-lg w-60 h-96 ">
                        <div class="relative p-2.5 h-96 overflow-hidden rounded-xl bg-clip-border">
                            <img
                            src="https://www.barcelona-tourist-guide.com/images/int/sport/barcelona-fc/L/fc-barcelona-0603.jpg"
                            alt="card-image"
                            class="h-full w-full object-cover rounded-md"
                          />
                        </div>
                        <div class="p-4">
                          <div class="mb-2 flex items-center justify-between">
                            <p class="text-slate-800 text-xl font-semibold">
    
                                <td>{{ court.court_name }}</td>
    
                            </p>
                            <p class="text-cyan-600 text-xl font-semibold">
    
                                <td>{{ court.court_type }} vs {{ court.court_type }}</td>
    
                            </p>
                          </div>
                          <p class="text-slate-600 leading-normal font-light">
    
                           Best football field
                          </p>

                          <p class="flex gap-3">
                            Availability: 
                            {% if court.availability == True %}
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                </svg>
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M18.364 18.364A9 9 0 0 0 5.636 5.636m12.728 12.728A9 9 0 0 1 5.636 5.636m12.728 12.728L5.636 5.636" />
                                </svg>
                            {% endif %}
                        </p>
                        
    
                        <form method="GET" action="{% url 'court:courtInfo' pk=court.pk %}">
                            <button type="submit" class="rounded-md w-full mt-6 bg-red-600 font-bold py-2 px-4 border border-transparent text-center text-sm text-white transition-all shadow-md hover:shadow-lg focus:bg-cyan-700 focus:shadow-none active:bg-cyan-700 hover:bg-cyan-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none">
                                Booking
                            </button>
                        </form>
                        </div>
                      </div>
                
        
                    {% endfor %}
                </div>

                </div>
                
            </div>
        {% else %}
            <h1>Please login</h1>
        {% endif %}
    {% endblock %}
</body>
</html>

court/templates/courtinfo.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
</head>
<body>
    {% block content %}
        {% if user.is_authenticated %}

            <nav class="bg-white border-gray-200 dark:bg-gray-900">
                <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

                    <a href="" class="flex items-center space-x-3 rtl:space-x-reverse">
                        
                        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Court Booking</span>
                    </a>

                <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

                    <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                        <div class="text-white w-fit p-2 flex justify-between gap-5 items-center">
                            {% if user.is_authenticated %}
                                <h1>Welcome, {{ user.username }}!</h1>
                            {% else %}
                                <h1>Welcome, Guest!</h1>
                            {% endif %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                                 <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                            </svg>   
                        </div>
                        

                    </button>
            
                </div>
                <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
                    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        
                        <li>
                            <a href="{% url 'court:courtlist'%}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Court</a>
                        </li>
                        <li>
                            <a href="{% url 'booking:booking_list' %}" class="block py-2 px-3 text-white rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Booking List</a>
                        </li>

                    </ul>
                </div>
                </div>
            </nav>

            <div>
                <div class="flex flex-row gap-5 p-5 justify-center">
               

                    <div class="bg-white max-w-2xl shadow overflow-hidden sm:rounded-lg">
                        <div class="px-4 py-5 sm:px-6">
                            <h3 class="text-lg leading-6 font-medium text-gray-900">
                                {{court.court_name}}
                            </h3>
                            <p class="mt-1 max-w-2xl text-sm text-gray-500">
                                {{court.court_type}} vs {{court.court_type}}
                            </p>
                        </div>
                        <div class="border-t border-gray-200  ">
                            <dl>
                                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                    <dt class="text-sm font-medium text-gray-500">
                                      Location 
                                    </dt>
                                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                        {{court.location}}
                                    </dd>
                                </div>
                                <div class="bg-white px-4 py-5 flex flex-row">
                                    <dt class="text-sm font-medium text-gray-500">
                                        Availability: 
                                    </dt>
                                    <d class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                      
                                        {% if court.availability == True %}
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                            </svg>
                                        {% else %}
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M18.364 18.364A9 9 0 0 0 5.636 5.636m12.728 12.728A9 9 0 0 1 5.636 5.636m12.728 12.728L5.636 5.636" />
                                            </svg>
                                        {% endif %}
                                    </d>
                                </div>
                               
                                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                        <img
                                        src="https://www.barcelona-tourist-guide.com/images/int/sport/barcelona-fc/L/fc-barcelona-0603.jpg"
                                        alt="card-image"
                                        class="h-full w-full object-cover rounded-md"
                                      />
                                    </dd>
                                </div>
                            </dl>
                        </div>
                    </div>
                
        
     
                </div>

                </div>
                
            </div>
        {% else %}
            <h1>Please login</h1>
        {% endif %}
    {% endblock %}
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>